version: "1"
rules:
  - base: master
    upstream: abpedroni:master    # change `abpedroni` to the owner of upstream repo
    mergeMethod: hardreset
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict