name: Automate PR Comments by Label

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
    - name: Print variables
      run: |
        echo "github.event.action >> ${{ github.event.action}}"
        echo "github.actor >> ${{ github.actor}}"
        echo "github.event_name >> ${{ github.event_name}}"
        echo "github.ref >> ${{ github.ref}}"

    - uses: actions/checkout@v2
      # with:
      #   ref: master

    - name: Label Commenter
      uses: peaceiris/actions-label-commenter@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .github/automate-comments-label-config.yml
